[package]
name = "helpman"
description = ""
license = "mit"
version = "0.1.0"
edition = "2024"
authors = ["James Vasile <jvasile@gmali.com>"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
